SELECT 
    trim("amazon-order-id") AS order_id,
    trim("merchant-order-id") AS merchant_order_id,
    "purchase-date"::timestamptz AS purchase_date,
    "last-updated-date"::timestamptz AS last_updated_date,
    trim("order-status") AS order_status,
    trim("fulfillment-channel") AS fulfillment_channel,
    trim("sales-channel") AS sales_channel,
    trim("order-channel") AS order_channel,
    trim(url) AS url,
    trim("ship-service-level") AS ship_service_level,
    trim("product-name") AS product_name,
    trim(sku) AS gbh_sku,
    trim(asin) AS asin,
    trim("item-status") AS item_status,
    quantity AS quantity,
    trim(currency )AS currency,
    replace(trim("item-price"),'$','')::decimal(10,2) AS item_price,
    replace(trim("item-tax"), '$','')::decimal(10,2) AS item_tax,
    replace(trim("shipping-price"), '$', '')::decimal(10,2) AS shipping_price,
    replace(trim("shipping-tax"), '$', '')::decimal(10,2) AS shipping_tax,
    replace(trim("gift-wrap-price"), '$', '')::decimal(10,2) AS gift_wrap_price,
    replace(trim("gift-wrap-tax"), '$', '')::decimal(10,2) AS gift_wrap_tax,
    replace(trim("item-promotion-discount"), '$', '')::decimal(10,2) AS item_promotion_discount,
    replace(trim("ship-promotion-discount"), '$', '')::decimal(10,2) AS ship_promotion_discount,
    trim("ship-city") AS ship_city,
    trim("ship-state") AS ship_state,
    "ship-postal-code" AS ship_postal_code,
    trim("ship-country") AS ship_country,
    trim("promotion-ids") AS promotion_ids
FROM {{source('raw_data', 'raw_amazon_orders')}}