SELECT
    TRIM("Name") AS order_id,
    TRIM(email) AS email,
    TRIM("Financial Status") AS financial_status,
	CAST(TRIM(REGEXP_REPLACE("Paid at", '\s[+-]\d{4}$', '')) AS TIMESTAMP) AS paid_at_ts,
    TRIM("Fulfillment Status") AS fulfillment_status,
	CAST(TRIM(REGEXP_REPLACE("Fulfilled at", '\s[+-]\d{4}$', '')) AS TIMESTAMP) AS fulfilled_at_ts,
    "Accepts Marketing" AS accepts_marketing,
    TRIM(currency) AS currency,
    REPLACE(REPLACE(TRIM(subtotal), '$', ''), ',', '')::DECIMAL(10,2) AS subtotal,
    REPLACE(REPLACE(TRIM(shipping), '$', ''), ',', '')::DECIMAL(10,2) AS shipping,
    REPLACE(REPLACE(TRIM(taxes), '$', ''), ',', '')::DECIMAL(10,2) AS taxes,
    REPLACE(REPLACE(TRIM(total), '$', ''), ',', '')::DECIMAL(10,2) AS total,
    TRIM("Discount Code") AS discount_code,
    CAST(REPLACE(TRIM("Discount Amount"), '$', '') AS DECIMAL(10,2)) AS discount_amount,
    TRIM("Shipping Method") AS shipping_method,
    CAST(TRIM(REGEXP_REPLACE("Created at", '\s[+-]\d{4}$', '')) AS TIMESTAMP) AS created_at_ts,
    "Lineitem quantity" AS lineitem_quantity,
    TRIM("Lineitem name") AS lineitem_name,
    "Lineitem price"::DECIMAL(10,2) AS lineitem_price,
    CAST(REPLACE(TRIM("Lineitem compare at price"), '$', '') AS DECIMAL(10,2)) AS lineitem_compare_at_price,
    TRIM("Lineitem sku") AS gbh_sku,
    "Lineitem requires shipping" AS lineitem_requires_shipping,
    "Lineitem taxable" AS lineitem_taxable,
    TRIM("Lineitem fulfillment status") AS lineitem_fulfillment_status,
    TRIM("Billing Name") AS billing_name,
    TRIM("Billing Street") AS billing_street,
    TRIM("Billing Address1") AS billing_address1,
    TRIM("Billing Address2") AS billing_address2,
    TRIM("Billing Company") AS billing_company,
    TRIM("Billing City") AS billing_city,
    TRIM("Billing Zip") AS billing_zip,
    TRIM("Billing Province") AS billing_province,
    TRIM("Billing Country") AS billing_country,
    TRIM("Billing Phone") AS billing_phone,
    TRIM("Shipping Name") AS shipping_name,
    TRIM("Shipping Street") AS shipping_street,
    TRIM("Shipping Address1") AS shipping_address1,
    TRIM("Shipping Address2") AS shipping_address2,
    TRIM("Shipping Company") AS shipping_company,
    TRIM("Shipping City") AS shipping_city,
    TRIM("Shipping Zip") AS shipping_zip,
    TRIM("Shipping Province") AS shipping_province,
    TRIM("Shipping Country") AS shipping_country,
    TRIM("Shipping Phone") AS shipping_phone,
    TRIM(notes) AS notes,
    TRIM("Note Attributes") AS note_attributes,
    CAST(TRIM(REGEXP_REPLACE("Cancelled at", '\s[+-]\d{4}$', '')) AS TIMESTAMP) AS cancelled_at_ts,
    TRIM("Payment Method") AS payment_method,
    TRIM("Payment Reference") AS payment_reference,
    CAST(REPLACE(TRIM("Refunded Amount"), '$', '') AS DECIMAL(10,2)) AS refunded_amount,
    TRIM(vendor) AS vendor,
    id AS id,
    TRIM(tags) AS tags,
    TRIM("Risk Level") AS risk_level,
    TRIM("Source") AS source,
    CAST(REPLACE(TRIM("Lineitem discount"), '$', '') AS DECIMAL(10,2)) AS lineitem_discount,
    TRIM("Tax 1 Name") AS tax_1_name,
    CAST(REPLACE(TRIM("Tax 1 Value"), '$', '') AS DECIMAL(10,2)) AS tax_1_value,
    TRIM("Tax 2 Name") AS tax_2_name,
    CAST(REPLACE(TRIM("Tax 2 Value"), '$', '') AS DECIMAL(10,2)) AS tax_2_value,
    TRIM("Tax 3 Name") AS tax_3_name,
    CAST(REPLACE(TRIM("Tax 3 Value"), '$', '') AS DECIMAL(10,2)) AS tax_3_value,
    TRIM("Tax 4 Name") AS tax_4_name,
    CAST(REPLACE(TRIM("Tax 4 Value"), '$', '') AS DECIMAL(10,2)) AS tax_4_value,
    TRIM("Tax 5 Name") AS tax_5_name,
    CAST(REPLACE(TRIM("Tax 5 Value"), '$', '') AS DECIMAL(10,2)) AS tax_5_value,
    TRIM(phone) AS phone,
    TRIM("Receipt Number") AS receipt_number,
    CAST(REPLACE(TRIM(duties), '$', '') AS DECIMAL(10,2)) AS duties,
    TRIM("Billing Province Name") AS billing_province_name,
    TRIM("Shipping Province Name") AS shipping_province_name,
    TRIM("Payment ID") AS payment_id,
    TRIM("Payment Terms Name") AS payment_terms_name,
    CAST(TRIM(REGEXP_REPLACE("Next Payment Due At", '\s[+-]\d{4}$', '')) AS TIMESTAMP) AS next_payment_due_at_ts,
    TRIM("Payment References") AS payment_references
FROM {{source('raw_data','raw_shopify_orders')}}